name: Files Sync Action
branding:
  color: blue
  icon: copy
description: Copies files from the action's environment (or any other repo) to many other repos.
inputs:
  GITHUB_TOKEN:
    description: Token to use to get repos and write secrets
    required: true
  TARGET_REPOS:
    description: |
      New line deliminated list of repositories. Repositires are limited to those in which the token user is an owner or collaborator. A custom branch can be defined for each repo by adding the branchname after a colon behind the repoSlug. `repoSlug` or `repoSlug:branchName`
    required: true
  FILE_LIST:
    description: |
      New line deliminated file paths to select files from the source repository. e.g. /.github/workflows/synced-deploy.yml
    required: true
  DRY_RUN:
    description: |
      Run everything except for the copying, removing and commiting functionality.
    required: false
    default: "false"
  COMMIT_MESSAGE:
    description: |
      The commit message that will be used to commit the changed files. Check the README for all interpolation options.
    required: false
    default: Update file(s) from \"%SRC_REPO%\"
  GIT_EMAIL:
    description: |
      The e-mail address used to commit the synced files. Defaults to $GITHUB_ACTOR@users.noreply.github.com
    required: false
  GIT_USERNAME:
    description: |
      The username used to commit the synced files. Defaults to $GITHUB_ACTOR
    required: false
  SKIP_DELETE:
    description: |
      Will omit all delete operations for matching files present in `TARGET_REPO` but not existant in `SRC_REPO` if set to `true`.
    required: false
    default: "false"
  SKIP_REPLACE:
    description: |
      Will omit all write operations for matching files present in `SRC_REPO` and `TARGET_REPO` if set to `true`.
    required: false
    default: "false"
  SKIP_CLEANUP:
    description: |
      If set to true or 1, the cleanup step to remove the temporary workding directory at the end will be skipped. Usefull for debugging purposes.
    required: false
    default: "false"
  SRC_REPO:
    description: |
      Repo from where files should be synced from. Defaults to $GITHUB_REPOSITORY. A custom branch can be defined by adding the branchname after a colon behind the SRC_REPO. `repoSlug` or `repoSlug:branchName`
    required: false
  TMPDIR:
    description: |
      The working directory where all sync operations will be done. Defaults to `tmp-${Date.now().toString()}`
    required: false
  SRC_ROOT:
    description: |
      Prepends this to all filepaths in the source repository.
    required: false
    default: /
  TARGET_ROOT:
    description: |
      Prepends this to all filepaths in the target repository.
    required: false
    default: /
runs:
  main: dist/index.js
  using: node12
